import { useTranslations } from "next-intl";

/**
 * V4-dictionary bridge (audit U-08). Message keys are deterministic slugs of
 * the English source string — generated by scripts/extract-i18n.mjs from the
 * vendored prototype (single source of truth). `useV4()` returns a translator
 * that falls back to the English literal when a string was never in the V4
 * dictionary, so missing entries degrade gracefully instead of rendering keys.
 */
export function slugifyV4(en: string): string {
  return (
    en
      .toLowerCase()
      .replace(/<[^>]+>/g, " ")
      .replace(/&amp;/g, "and")
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 56)
      .replace(/_+$/g, "") || "s"
  );
}

export function useV4() {
  const t = useTranslations("v4");
  return (en: string): string => {
    const key = slugifyV4(en);
    return t.has(key) ? t(key) : en;
  };
}

/** Rich-text keys (hero.title etc.) — use with t.rich in components. */
export function useV4Rich() {
  return useTranslations("v4");
}
